### ISSUE TITLE
Release 1.5.x

### ISSUE THREAD

**Issue by ynqa** [ynqa/pandavro#17]
### Overview

Use git tag to upload for PyPI #16.

Release 1.5.x:
- [x] Fix incorrect type inference, Python compatibility issues, support compression #12 @dargueta 
- [x] Feature/add support append file #13 @AlanTaranti
- [x] Add section to README that explains how pandavro infers schema #15 @The-Fonz
- [x] Use tags for deploy #16 @ynqa

**Comment by ynqa** [comment]
Finished to release and upload to PyPI
- https://github.com/ynqa/pandavro/releases/tag/v1.5.0
- https://pypi.org/project/pandavro/1.5.0
